site_name: TeslaMind
theme:
  name: material
nav:
  - Home: index.md
  - Usage: usage.md
  - CLI: cli.md
  - Modes: modes.md
  - Personas: personas.md
  - Scoring: score.md
  - Advanced: advanced.md
  - API Reference: api.md
  - Contributing: contribute.md
